# Generated by Django 3.2.9 on 2021-11-22 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='author',
        ),
        migrations.AddField(
            model_name='comment',
            name='author_name',
            field=models.CharField(default='null', max_length=50, verbose_name='Имя автора'),
            preserve_default=False,
        ),
    ]
