# Generated by Django 3.2.9 on 2021-11-23 10:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articles', '0003_ratingstar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ratingstar',
            options={'ordering': ['-value'], 'verbose_name': 'Звезда рейтинга', 'verbose_name_plural': 'Звёзды рейтинга'},
        ),
        migrations.RemoveField(
            model_name='ratingstar',
            name='article',
        ),
        migrations.RemoveField(
            model_name='ratingstar',
            name='user',
        ),
        migrations.AddField(
            model_name='article',
            name='avg_rating',
            field=models.FloatField(default=0, verbose_name='Рейтинг'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.article')),
                ('star', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.ratingstar')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Рейтинг',
                'verbose_name_plural': 'Рейтинги',
            },
        ),
    ]
