# Generated by Django 3.2.9 on 2021-11-23 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20211123_1329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='avg_rating',
        ),
    ]
