# Generated by Django 3.2.9 on 2021-11-24 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_alter_article_likes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='like',
            options={'verbose_name': 'Лайк', 'verbose_name_plural': 'Лайки'},
        ),
        migrations.AlterField(
            model_name='like',
            name='type_like',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Не лайкнуто'), (1, 'Лайкнуто')]),
        ),
    ]
