# Generated by Django 3.2.9 on 2021-11-24 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0011_auto_20211124_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='type_like',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Не лайкнуто'), (1, 'Лайкнуто')], default=0),
        ),
    ]
