# Generated by Django 3.2.9 on 2021-11-26 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0012_alter_like_type_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='likes',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество лайков'),
        ),
    ]
