# Generated by Django 3.2.9 on 2021-11-27 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0014_article_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='group',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Книги'), (1, 'Игры'), (3, 'Фильмы')], default=0),
        ),
    ]
