# Generated by Django 3.2.9 on 2021-11-28 15:45

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0017_alter_article_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_text_en',
            field=tinymce.models.HTMLField(null=True, verbose_name='Текст статьи'),
        ),
        migrations.AddField(
            model_name='article',
            name='article_text_ru',
            field=tinymce.models.HTMLField(null=True, verbose_name='Текст статьи'),
        ),
        migrations.AddField(
            model_name='article',
            name='article_title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Название статьи'),
        ),
        migrations.AddField(
            model_name='article',
            name='article_title_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Название статьи'),
        ),
        migrations.AddField(
            model_name='article',
            name='group_en',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Книги'), (2, 'Игры'), (3, 'Фильмы')], default=0, null=True, verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='article',
            name='group_ru',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Книги'), (2, 'Игры'), (3, 'Фильмы')], default=0, null=True, verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='comment',
            name='comment_text_en',
            field=models.CharField(max_length=300, null=True, verbose_name='Текст комментария'),
        ),
        migrations.AddField(
            model_name='comment',
            name='comment_text_ru',
            field=models.CharField(max_length=300, null=True, verbose_name='Текст комментария'),
        ),
        migrations.AddField(
            model_name='rating',
            name='rate_en',
            field=models.PositiveSmallIntegerField(choices=[(1, '1 - Ужасно'), (2, '2 - Плохо'), (3, '3 - Нормально'), (4, '4 - Хорошо'), (5, '5 - Великолепно')], null=True),
        ),
        migrations.AddField(
            model_name='rating',
            name='rate_ru',
            field=models.PositiveSmallIntegerField(choices=[(1, '1 - Ужасно'), (2, '2 - Плохо'), (3, '3 - Нормально'), (4, '4 - Хорошо'), (5, '5 - Великолепно')], null=True),
        ),
    ]
