# Generated by Django 3.2.9 on 2021-11-28 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0018_auto_20211128_1845'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='article_text_en',
        ),
        migrations.RemoveField(
            model_name='article',
            name='article_text_ru',
        ),
        migrations.RemoveField(
            model_name='article',
            name='article_title_en',
        ),
        migrations.RemoveField(
            model_name='article',
            name='article_title_ru',
        ),
        migrations.RemoveField(
            model_name='article',
            name='group_en',
        ),
        migrations.RemoveField(
            model_name='article',
            name='group_ru',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='comment_text_en',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='comment_text_ru',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='rate_en',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='rate_ru',
        ),
    ]
