# Generated by Django 3.2.9 on 2021-11-29 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0019_auto_20211128_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='group',
            field=models.CharField(choices=[('Книги', 'Книги'), ('Игры', 'Игры'), ('Фильмы', 'Фильмы')], default='', max_length=6, verbose_name='Категория'),
        ),
    ]
