# Generated by Django 3.2.9 on 2021-11-29 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0020_alter_article_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='author_mark',
            field=models.PositiveSmallIntegerField(choices=[], default=0, verbose_name='Оценка автора'),
        ),
    ]
