# Generated by Django 3.2.9 on 2021-11-29 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0021_article_author_mark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='author_mark',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1 - Отвратительно'), (2, '2 - Ужасно'), (3, '3 - Плохо'), (4, '4 - Удовлетворительно'), (5, '5 - Нормально'), (6, '6 - Хорошо'), (7, '7 - Очень хорошо'), (8, '8 - Замечательно'), (9, '9 - Прекрасно'), (10, '10 - Шедеврально')], default=0, verbose_name='Оценка автора'),
        ),
    ]
